objects:
  aruco_cube_111: 
    aruco:
      id:
        111
    position:
      x: 1.1
      y: 1.82
      z: 0.8625
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.977
  aruco_cube_222: 
    aruco:
      id:
        222
    position:
      x: 1.82
      y: -0.25
      z: 0.8625
    orientation:
      x: 0.0
      y: 0.0
      z: -1.57
      w: 0.998
  aruco_cube_333: 
    aruco:
      id:
        333
    position:
      x: 1.82
      y: 0.0
      z: 0.8625
    orientation:
      x: 0.0
      y: 0.0
      z: -1.57
      w: 0.986
  aruco_cube_444: 
    aruco:
      id:
        444
    position:
      x: 1.82
      y: 0.25
      z: 0.8625
    orientation:
      x: 0.0
      y: 0.0
      z: -1.57
      w: 0.999
  aruco_cube_582:
    aruco:
      id:
        582
    position:
      x: 0.7
      y: 1.82
      z: 0.8625
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.804
