name: mp-iv
channels:
  - conda-forge
  - defaults
  - open3d-admin
dependencies:
  - ipython=7.20 # a powerful Python shell
  - jupyter=1.0 # to edit and run Jupyter notebooks
  - matplotlib=3.3 # beautiful plots. See tutorial tools_matplotlib.ipynb
  - numpy=1.19 # Powerful n-dimensional arrays and numerical computing tools
  - python=3.7 # Python! Not using latest version as some libs lack support
  - scikit-learn=0.24 # machine learning library
  - scikit-image # machine learning library
  - scipy=1.6 # scientific/technical computing library
  - shapely=1.8.0
  - ffmpeg
  - k3d=2.10.0 # Visualization library
  - opencv=4.5.2 # computer vision library
  - ipympl=0.7.0
  - jupyter_client=6.1.12 # needs to be <7 to have nbgrader working. "TypeError: 'coroutine' object is not subscriptable" (https://github.com/jupyter/jupyter_client/issues/637#issuecomment-902149763)
  - nbgrader=0.6.2
  - nest-asyncio=1.5.1
  - sqlalchemy=1.3.23 # Need to downgrade because otherwise autograding will run into an issue (issue for nbgrader<=0.5.6: https://github.com/jupyter/nbgrader/issues/1073, issue for nbgrader>0.6: https://github.com/jupyter/nbgrader/issues/1426)
  - tqdm=4.62.2 # progress bars
  - open3d=0.13.0 # 3D point cloud algorithms
  - transforms3d=0.3.1
  - funcy=1.16 # for timing
  - six=1.15.0 # dependency of pip tensorflow below
  - typing-extensions=3.7.4.3 # dependency of pip tensorflow below
  - nbqa=1.1.1 # code quality (jupyter notebooks)
  - pylint=2.10.2 # code quality
  - mypy=0.910 # code quality
  - pyupgrade=2.29.0 # code quality
  - flake8=3.9.2 # code quality
  - isort=5.9.3 # code quality
  - pip=21.2.4
  - pip:
    - ipynb==0.5.1 # import symbols from other notebooks
    - tensorflow==2.4.1 # machine learning library
    - black[jupyter]==21.7b0  # code formatting and checking (no jupyter files for now due to depencendy conflict with tensorflow (typing-extensions 3.7.4 (tf) vs 3.10 (black)))
    - vulture==2.3
