[tool.black]
line-length = 120
target-version = ['py37',]

[tool.nbqa.exclude]
pylint = "answer_resources"

[tool.isort]
line_length = 120
multi_line_output = 3  # compatible with black
include_trailing_comma = true  # compatible with black

[tool.vulture]
exclude = [
    "ta_tools",
    "answer_resources",
    "trackeval",
    "checkpoint",
    "deprecated",
]
ignore_names = [
    "camera",  # k3d plot.camera setting
    "call",  # tensorflow calls
]